export const metadata = {
  title: 'Privacy Policy — Thiam Language Translator',
};

export default function PrivacyPage() {
  return (
    <main style={styles.container}>
      <h1 style={styles.h1}>Privacy Policy — Thiam Language Translator</h1>
      <p style={styles.meta}>Last updated: October 3, 2026</p>

      <hr style={styles.hr} />

      <h2 style={styles.h2}>What This App Does</h2>
      <p style={styles.p}>
        Thiam Language Translator takes a phrase you speak or type, translates it into your chosen
        language, and plays the translation aloud. In practice mode you can say the translation
        back and see how closely it matched. No account or login is required.
      </p>

      <h2 style={styles.h2}>Data We Collect</h2>
      <table style={styles.table}>
        <thead>
          <tr>
            <th style={styles.th}>Data</th>
            <th style={styles.th}>Why</th>
            <th style={styles.th}>How long</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={styles.td}><strong>Voice recordings</strong> (a phrase to translate, or a practice attempt)</td>
            <td style={styles.td}>To turn your speech into text</td>
            <td style={styles.td}>Sent to OpenAI, not stored by us</td>
          </tr>
          <tr>
            <td style={styles.td}><strong>Text you speak or type, and its translation</strong></td>
            <td style={styles.td}>To translate it and to generate the spoken audio</td>
            <td style={styles.td}>
              Sent to OpenAI. For Wolof and Bambara audio, the translation is sent to our own voice
              server. Not stored by us (see Data Storage)
            </td>
          </tr>
          <tr>
            <td style={styles.td}><strong>Source and target language</strong></td>
            <td style={styles.td}>To perform the correct translation</td>
            <td style={styles.td}>Sent with the request; kept only in technical logs without your text</td>
          </tr>
          <tr>
            <td style={styles.td}><strong>Random app-install ID and IP address</strong></td>
            <td style={styles.td}>To limit how many requests one device or network can make, which prevents abuse</td>
            <td style={styles.td}>Only a one-way hash is kept, for at most one hour</td>
          </tr>
        </tbody>
      </table>
      <p style={styles.p}>
        The app-install ID is a random number the app creates the first time it runs. It is not
        linked to you, your device&apos;s hardware or advertising identifiers, or any account. We do
        not collect your name, email address, location, or any other personal information.
      </p>

      <h2 style={styles.h2}>How Your Data Is Used</h2>
      <p style={styles.p}>
        Your requests pass through our backend to <strong>OpenAI</strong> (openai.com) for
        processing:
      </p>
      <ol style={styles.ol}>
        <li style={styles.li}>Voice recording → OpenAI speech-to-text</li>
        <li style={styles.li}>Spoken or typed text → OpenAI translation</li>
        <li style={styles.li}>Translation → OpenAI text-to-speech audio</li>
      </ol>
      <p style={styles.p}>
        <strong>Wolof and Bambara audio:</strong> OpenAI&apos;s voices do not cover these two
        languages, so their audio is generated by a voice server that we operate ourselves. Only
        the translated text and the language are sent to it. The translation itself is still done
        by OpenAI.
      </p>
      <p style={styles.p}>
        <strong>Practice mode:</strong> when you say a translation back, only your recording and
        the language are sent, to be turned into text. The phrase you were practicing is not sent
        with it, and your score is calculated on your device.
      </p>
      <p style={styles.p}>
        OpenAI&apos;s privacy policy is available at:{' '}
        <a href="https://openai.com/policies/privacy-policy" style={styles.a}>
          https://openai.com/policies/privacy-policy
        </a>
      </p>

      <h2 style={styles.h2}>Stored On Your Device Only</h2>
      <ul style={styles.ul}>
        <li style={styles.li}>
          Your practice list (the phrases you star), your scores and your practice streak.
        </li>
        <li style={styles.li}>The random app-install ID, and whether you agreed to the data notice.</li>
      </ul>
      <p style={styles.p}>
        These never leave your device, except that opening a saved phrase sends its text again to
        generate the audio. Deleting the app deletes them.
      </p>

      <h2 style={styles.h2}>Data Storage</h2>
      <ul style={styles.ul}>
        <li style={styles.li}>We do not store your voice recordings.</li>
        <li style={styles.li}>We do not store your text or translations in any database or file.</li>
        <li style={styles.li}>We do not have a database of user data.</li>
        <li style={styles.li}>
          Our Wolof and Bambara voice server may keep recently generated audio, together with the
          text it was made from, in temporary memory so that a repeated phrase plays faster. It is
          never written to disk, is not linked to any device or person, and is erased when the
          server restarts.
        </li>
        <li style={styles.li}>
          Technical logs record that a request happened: the time, language codes, sizes, how long
          it took, the app version and whether it succeeded. They never contain your recordings,
          your text or your translations.
        </li>
        <li style={styles.li}>
          To prevent abuse, request counters keyed by a one-way hash of the app-install ID and IP
          address are kept by Upstash (our rate-limiting provider) and expire within one hour.
        </li>
      </ul>

      <h2 style={styles.h2}>Third-Party Services</h2>
      <p style={styles.p}>This app uses the following services:</p>
      <ul style={styles.ul}>
        <li style={styles.li}>
          <strong>OpenAI</strong> — for speech-to-text, translation, and text-to-speech. Subject to
          OpenAI&apos;s privacy policy and terms of service.
        </li>
        <li style={styles.li}>
          <strong>Vercel</strong> — hosts our backend, which forwards your requests and returns the
          results.
        </li>
        <li style={styles.li}>
          <strong>Hetzner</strong> — hosts the voice server we operate for Wolof and Bambara audio.
        </li>
        <li style={styles.li}>
          <strong>Upstash</strong> — for rate limiting. Receives only hashed identifiers, never your
          audio or text.
        </li>
      </ul>

      <h2 style={styles.h2}>Microphone Permission</h2>
      <p style={styles.p}>
        The app requests access to your device&apos;s microphone solely to record a phrase for
        translation or a practice attempt. Microphone access is only active while you are actively
        recording. We do not record audio in the background. You can use the app without the
        microphone by typing your phrase.
      </p>

      <h2 style={styles.h2}>Children&apos;s Privacy</h2>
      <p style={styles.p}>
        This app is rated 4+ / Everyone and does not knowingly collect data from children under 13.
      </p>

      <h2 style={styles.h2}>Changes to This Policy</h2>
      <p style={styles.p}>
        If we update this privacy policy, we will update the &quot;Last updated&quot; date at the
        top of this page.
      </p>

      <h2 style={styles.h2}>Contact</h2>
      <p style={styles.p}>
        If you have questions about this privacy policy, contact us at:{' '}
        <a href="mailto:alphathiam@icloud.com" style={styles.a}>
          alphathiam@icloud.com
        </a>
      </p>
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    maxWidth: 720,
    margin: '0 auto',
    padding: '48px 24px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    color: '#1a1a1a',
    lineHeight: 1.7,
  },
  h1: {
    fontSize: 28,
    fontWeight: 700,
    marginBottom: 8,
  },
  h2: {
    fontSize: 20,
    fontWeight: 600,
    marginTop: 36,
    marginBottom: 8,
  },
  meta: {
    color: '#666',
    fontSize: 14,
    marginBottom: 24,
  },
  hr: {
    border: 'none',
    borderTop: '1px solid #e5e5e5',
    marginBottom: 32,
  },
  p: {
    marginBottom: 16,
  },
  ul: {
    paddingLeft: 24,
    marginBottom: 16,
  },
  ol: {
    paddingLeft: 24,
    marginBottom: 16,
  },
  li: {
    marginBottom: 8,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: 16,
  },
  th: {
    textAlign: 'left',
    padding: '8px 12px',
    backgroundColor: '#f5f5f5',
    borderBottom: '2px solid #e5e5e5',
    fontSize: 14,
    fontWeight: 600,
  },
  td: {
    padding: '8px 12px',
    borderBottom: '1px solid #e5e5e5',
    fontSize: 14,
  },
  a: {
    color: '#0070f3',
  },
};
